### ISSUE TITLE
ESM bundle polyfills require globally

### ISSUE THREAD

**Issue by bluwy** [tinylibs/tinyexec#23]
I noticed in the latest release with https://github.com/tinylibs/tinyexec/pull/21, it assigns `globalThis.require` globally if it doesn't exist in ESM. I'm not sure this is safe and correct. It may indirectly allow other invalid code that calls the global require in ESM to work, which it shouldn't by default.

Maybe there's a way to polyfill the require for this ESM bundle only. Would a top level `const require = ...` work?

**Comment by 43081j** [comment]
im really stuck on what to do here in that case, esbuild is causing us hell

basically it turns out esbuild outputs invalid code. it outputs esm bundles containing require() calls still, which is ofc invalid

maybe we'll just have to move cross-spawn into this repo instead 🤷
