### ISSUE TITLE
Has default timeout of 4000ms

### ISSUE THREAD

**Issue by bluwy** [tinylibs/tinyexec#29]
It looks like the library has 4000ms timeout by default:

https://github.com/tinylibs/tinyexec/blob/9bbc2b46287644b2473489cc57d8b6df6da163b8/src/main.ts#L50

It doesn't seem documented and caught me off guard when migrating from execa. Should it not have an opinionated timeout by default?

**Comment by benmccann** [comment]
Also reported in https://github.com/antfu/install-pkg/pull/12

I agree there should not be a timeout by default

**Comment by antfu** [comment]
Do you plan to fix it soon? Otherwise I think I would need to revert https://github.com/antfu/install-pkg/pull/12 first

**Comment by bluwy** [comment]
It can be worked around with `{ nodeOptions: { timeout: undefined } }` so that it overrides the default.

**Comment by benmccann** [comment]
Code was updated, but it will be another couple of days before a release can be made

**Comment by benmccann** [comment]
Released in 0.2.0
