### ISSUE TITLE
Environment variable not passing correctly

### ISSUE THREAD

**Issue by WooWan** [tinylibs/tinyexec#37]
## Description
When using tinyexec to spawn a child process with custom environment variables, the variables are not correctly set in the child environment. Specifically, running a command with console.log(process.env.MY_VARIABLE) results in undefined instead of the expected value, even though MY_VARIABLE is specified in the env option.

## Reproduce
```ts

import { x } from "tinyexec";

async function spawnChildProcessTiny() {
  const { stdout } = await x(
    "node",
    ["-e", "console.log(process.env.MY_VARIABLE)"],
    {
      env: { ...process.env, MY_VARIABLE: "hello" },
    }
  );
  console.log(`Child process output: ${stdout}`);
}

spawnChildProcessTiny();

```

The output should print hello as the value of MY_VARIABLE in the child process.

Actual Behavior
The output is undefined, indicating that the variable is not passed correctly to the child process.

Is it a expected behaviour? If not can I give it a try to fix it?

**Comment by 43081j** [comment]
It isn't expected behaviour

The `env` you pass is already merged with `process.env` FYI. You don't need to spread that yourself

We have tests covering this and they pass fine. So I'm curious why you're not seeing the same success. Could well be a bug but we will need to debug
