### ISSUE TITLE
Suggest a library to parse string commands

### ISSUE THREAD

**Issue by antfu** [tinylibs/tinyexec#42]
In `execa` it allows users to use a single string as command, like `execa.command('foo bar -m "message with space"')`

I understand that `tinyexec` is trying to be as lightweight as possible, while string commands can be easily migrated if it's hard coded, but it would be tricky when you have the command from user input.

A straightforward solution is that people might do:

```ts
const args = command.split(' ')
const process = x(args[0], args.slice(1))
```

But this would be an extremely dangerous approach as it didn't handle many cases well - while a huge amount of developers might not even realize this when writing such code.

I would suggest documenting a few recommended tiny libraries that will parse shell args safely to cover this missing feature when migrating `execa` to `tinyexec`, for example.

**Comment by antfu** [comment]
What I found was https://www.npmjs.com/package/shell-quote 

Or maybe `tinyexec` could have that feature as a tree-shakable export or so directly?

**Comment by 43081j** [comment]
a lot of the bloat in other exec packages is to support stuff like this, so I think it belongs in another package for sure

I'm not sure there's any already established package to do it though. may be a good opportunity to create a new tiny alternative if so 👀

**Comment by TrySound** [comment]
Hey, I just built small tokenizer for commands and arguments
https://github.com/TrySound/args-tokenizer

```js
import { tokenizeArgs } from "args-tokenizer";
import { x } from "tinyexec";

const [command, ...args] = tokenizeArgs("ls -la");
const result = await x(command, args);
console.log(result.stdout);
```

**Comment by TrySound** [comment]
@43081j Good to close?
